# Generated by Django 5.1.6 on 2025-02-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_type', models.CharField(max_length=500)),
                ('Total_courses', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='coarse_category_images')),
            ],
        ),
        migrations.CreateModel(
            name='Course_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_image', models.ImageField(blank=True, null=True, upload_to='coarse_image/')),
            ],
        ),
        migrations.CreateModel(
            name='New_Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('designation', models.CharField(choices=[('Mwenyekiti', 'Mwenyekiti'), ('Katibu', 'Katibu'), ('Mhasibu', 'Mhasibu')], max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Popular_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=500)),
                ('Student_enroll', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='popular_coarse_images')),
            ],
        ),
        migrations.CreateModel(
            name='Student_testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=255)),
                ('Profession', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_images/')),
                ('designation', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
