# Generated by Django 5.1.6 on 2025-02-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_gallery',
            name='image_name',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
