# Generated by Django 5.1.6 on 2025-02-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_testimonial')),
            ],
        ),
    ]
