# Generated by Django 5.1.6 on 2025-02-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_user_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direct_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('service_type', models.CharField(max_length=255)),
            ],
        ),
    ]
