# Generated by Django 5.1.6 on 2025-02-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_direct_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='direct_service',
            name='phone_number',
            field=models.IntegerField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
