# Generated by Django 5.1.1 on 2025-05-08 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_course_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ebenezeri Mind Education')),
                ('service_start_date', models.DateField(default=datetime.datetime(2025, 2, 20, 0, 0))),
                ('payment_start_date', models.DateField(default=datetime.datetime(2025, 4, 22, 0, 0))),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='direct_service',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
