# Generated by Django 5.1.1 on 2025-05-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_hostingpayment_alter_direct_service_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_admin_link', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HostingPayment',
        ),
    ]
